environment = "test"

[http]

[[http.server]]
listen = ["80"]
serverName = ["codebox-test.sdkwork.com", "codebox-test.birdcoder.com", "codebox-test.dtupay.com", "codebox-test.noaper.com", "codebox-test.sdkwork.cn", "codebox-test.birdcoder.cn", "codebox-test.dtupay.cn", "codebox-test.noaper.cn", "codebox-test.skubc.com", "codebox-test.skubc.cn", "codebox-test.zowalk.com", "codebox-test.zowalk.cn", "codebox-test.offer86.com", "codebox-test.offer86.cn", "codebox-test.86offer.com", "codebox-test.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.nonproduction.conf"]

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

